name: create-release
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest release
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: nakahashi
          repo: electron-boilerplate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: cat ${{ steps.get_latest_release.outputs.data }} | jq -r .tag_name

      - name: Get latest tag
        id: get_latest_tag
        run: |
          git fetch --prune --unshallow
          echo "data=$(git describe --tags --abbrev=0)" >> "$GETHUB_OUTPUT"
      - run: "echo Release found: '${{ steps.get_latest_tag.outputs.data }}'"
