name: create-release
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo $PATH
