name: create-release
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest release
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: nakahashi
          repo: electron-boilerplate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set latest release
        run: |
          echo "latest_release=$(echo '${{ toJSON(steps.get_latest_release.outputs.data) }}' | jq -r .tag_name" >> $GITHUB_ENV

      - name: Get latest tag
        run: |
          git fetch --prune --unshallow
          echo "get_latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.get_latest_tag }}"
