name: create-release
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
          # echo "latest_release=$(echo '${{ toJSON(steps.get_latest_release.outputs.data) }}' | jq .tag_name" >> $GITHUB_ENV
          # release=$(echo ${{ steps.get_latest_release.outputs.data }} | jq .tag_name)

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest release
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: nakahashi
          repo: electron-boilerplate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set latest release
        run: |
          echo "latest_release=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.latest_release }}"

      - name: Set latest tag
        run: |
          git fetch --prune --unshallow
          echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.latest_tag }}"

      - name: Create release
        if: env.latest_release != env.latest_tag
        run: echo "create!!"

      - name: Keep release
        if: env.latest_release == env.latest_tag
        run: echo "keep!!"
