name: create-release
on:
  workflow_dispatch:
  # push:
  #   branches: [ main ]
          # echo "latest_release=$(echo '${{ toJSON(steps.get_latest_release.outputs.data) }}' | jq .tag_name" >> $GITHUB_ENV
          # release=$(echo ${{ steps.get_latest_release.outputs.data }} | jq .tag_name)

jobs:
  create-releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get latest release
        uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/{owner}/{repo}/releases/latest
          owner: nakahashi
          repo: electron-boilerplate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set latest release
        run: |
          echo "latest_release=${{ fromJson(steps.get_latest_release.outputs.data).tag_name }}" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.latest_release }}"

      - name: Set latest tag
        run: |
          git fetch --prune --unshallow
          echo "latest_tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_ENV"
      - run: |
          echo "${{ env.latest_tag }}"

      - name: Set release name
        env:
          TZ: 'Asia/Tokyo'
        run: |
          datetime_name=$(date +'%Y%m%d-%H%M')
          echo "release_name=${{'v'}}${{$datetime_name}} >> $GITHUB_ENV

      - name: Create release
        # if: env.latest_release != env.latest_tag
        # uses: actions/create-release@v1
        # env:
        #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # with:
        #   tag_name: ${{ env.latest_tag }}
        #   release_name: ${{ env.release_name }}
        run: |
          echo "${{ env.release_name }}"
